project:
  type: website
  output-dir: docs

website:
  title: "Beril Yıldız's Analytics Lab"
  navbar:
    search: true
    left:
      - text: Home
        href: index.qmd
        icon: house
      - text: About Me
        href: about.qmd
        icon: person
      - text: My Posts
        href: posts.qmd
        icon: file-earmark-text
      - text: "EMU430 Coursework"
        menu:
          - text: Assignments
            href: assignments.qmd
            icon: clipboard
          - text: Project
            href: project.qmd
            icon: bar-chart

    tools:
      - icon: github
        href: https://github.com/berilyldz
      - icon: linkedin
        href: https://www.linkedin.com/in/beril-yildiiz/
        
  sidebar:
    - title: "Assignments"
      style: "docked"
      search: true
      contents:
        - assignments.qmd
        - assignments/assignment-1.qmd
        - assignments/assignment-2.qmd
      collapsible: true # Optionally, make the sidebar collapsible

  page-navigation: true
  back-to-top-navigation: true
  page-footer:
    center: "Hacettepe IE - EMU430 - 2024 Fall | All rights reserved."
    border: true

format:
  html:
    toc: true
    toc-location: left
    theme: 
      light: pulse 
      dark: superhero
    css: styles.css

editor: visual
